// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock2Shop.Infrastructure.Data;

#nullable disable

namespace Stock2Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20241212135809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Stock2Shop.Core.Models.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sku");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
